#ifndef CONSTANTS_H
#define CONSTANTS_H

#define CUSTOM_SERVERADDRESS "127.0.0.1"
#define CUSTOM_PORT 5001

#define CUSTOM_SENSOR01 112
#define CUSTOM_SENSOR02 121
#define CUSTOM_SENSOR03 211

#define COMMAND_GET 'g'
#define COMMAND_SET 's'
#define COMMAND_ERROR 'e'

#endif // CONSTANTS_H
